theme: minima

siteConfig:
  title: Joshua Voydik
  author:   ㅤ     
  description:  ㅤ

themeConfig:
  nav:
    - text:
      link: /
    - text: About
      link: /about.html
  social:
    twitter: joshuavoydik
    linkedin: joshvoydik

plugins:
  - resolve: saber-plugin-query-posts
    options:
      atomFeed: true
